FROM jenkins/jenkins:lts-jdk17

USER root


RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    zip \
    wget \
    unzip \
    jq


RUN wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com bookworm main" | tee /etc/apt/sources.list.d/hashicorp.list
RUN apt-get update && apt-get install -y terraform


RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" \
    && unzip awscliv2.zip \
    && ./aws/install \
    && rm -rf aws awscliv2.zip






RUN rm /usr/lib/python3.11/EXTERNALLY-MANAGED || true 


RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

USER jenkins
